# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'NLiteAVDemo' do
  use_frameworks!
  # 云信基础SDK
  pod 'NERtcSDK', '5.5.2'
  pod 'NIMSDK_LITE', '9.14.0'
  
  pod 'NECallKitPstn', :path => 'CallKit/NECallKitPstn/NECallKitPstn.podspec'

  # 三方依赖
  pod 'Masonry'
  
  #呼叫组件API组件
  pod 'NERtcCallKit', '2.2.2'
  
  #呼叫组件UI组件
  pod 'NERtcCallUIKit', '2.2.2'
  
  pod 'NETranscodingKit'
  
  #如果需要查看呼叫组件UI组件源码请注释远端引用，打开下面本地引用
  #pod 'NERtcCallUIKit', :path => 'CallKit/NERtcCallUIKit/NERtcCallUIKit.podspec'


end
