# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NLiteAVDemo' do
  use_frameworks!

pod 'NERtcSDK', '~> 3.5.1'
pod 'NIMSDK_LITE', '7.8.4'
pod 'Masonry'
pod 'SDWebImage', '~> 5.7.1'
pod 'Toast'
end
