# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'NLiteAVDemo' do
  use_frameworks!
  pod 'ReactiveObjC'
  pod 'Masonry'
  pod 'SDWebImage', '~> 5.7.1'
  pod 'Toast'
  pod 'AFNetworking', '4.0'
  pod 'NIMSDK_LITE', '9.10.0'
  pod 'GCDWebServer', '~> 3.5.4'
  pod 'NERtcSDK', '4.6.50'
  pod 'NECallKitPstn', '1.8.0'
  
  #呼叫组件API组件
  pod 'NERtcCallKit', '2.0.0'
  
  #呼叫组件UI组件
  pod 'NERtcCallUIKit', '2.0.0'
  
  #如果需要查看呼叫组件UI组件源码请注释远端引用，打开下面本地引用
  #pod 'NERtcCallUIKit', :path => 'CallKit/NERtcCallUIKit/NERtcCallUIKit.podspec'
end
